### PR TITLE
Skip heavily damaged attention for safe nodes

### PR DESCRIPTION
**Pull request by vuryleo**
Sometimes it's safe to keep moving even when some ships are heavily damaged, for there's no battle afterwards.

PS: No ship sank during testing.

### CODE REVIEW

**Comment by KagamiChan** [comment]
Personally I prefer not to hardcode such condition check because
- The map data, including nodes, enemies, behaviours could suddenly change after a maintenance. Although we have not seen such happening so far, but it is possible.
- normal players are expected to hit this warning case at most 7 times per month, and false warnings at this rate are tolerable in my opinion

Anyway I‘m still open for discussion

**Comment by vuryleo** [comment]
The same thing happens with 2-3/4-4 etc (with possibility though). I just put 1-6 here for I came up with this idea when working on this one.

**Comment by vuryleo** [comment]
If you still have concern we may put these data in fcd/map, which won't work if the API changes.

**Comment by KagamiChan** [comment]
If you want to cover all these conditions, the hardcoding or data maintenance could be complicated and tricky. Maybe you may check next spot kind/event classification function in Prophet plugin.

But in fact, players themselves are fully responsible for determining whether to keep going next given kanmusu heavily damaged. IMO poi dose not, and will never tend to take care of this

**Comment by KagamiChan** [comment]
forgot to give you a link: https://github.com/poooi/plugin-prophet/blob/master/utils.es#L97, my apology

**Comment by Javran** [comment]
- perhaps not fcd/map as it's generated from other sources, try fcd/safe-nodes or whatever in parallel to fcd/map
- would prefer marking "safe nodes" over marking "safe edges" due to the natural of this problem, and it's possible for multiple edges ending up going to the same node

**Comment by KagamiChan** [comment]
one thing to note: route/node added should be carefully and thoroughly tested :(

**Comment by KochiyaOcean** [comment]
put data in a new fcd section would be better

**Comment by yukixz** [comment]
Collect map/next data using plugin-report, then we can generate safe route automatically.

**Comment by yukixz** [comment]
@yukixz Considering a sitution: A-B-C-D. A, D are battle spot, C, D are battle-avoid spot.
If ship get heavy damaged on battle spot A, should we popup the confirm?
There is no in-game confirm on route B-C and C-D.

**Pull request closed without merging**
