### PR TITLE
Single poi instance

### PR DESCRIPTION
**Pull request by alvin-777**
要多开的话用
`electron poi --multiple-instance`
or
`electron poi -m`

### CODE REVIEW

**Comment by yukixz** [comment]
i18n request.

**Comment by yukixz** [comment]
咦=。= 还不墨迹么

**Comment by dkwingsmt** [comment]
> Another instance of poi is running. 
> It may have been hidden. You can choose to show it,
> or to open another poi instance anyway if that doesn't work.
> [Show the previous instance] [Open a new instance] [Quit]

**Comment by wudifeixue** [comment]
Why is this pull request open for almost a year?

**Pull request closed without merging**
