### PR TITLE
Add svg icons

### PR DESCRIPTION
**Pull request by magicae**
+ Add svg icons designed by @edwardaaaa
+ Add settings
+ Add COPYRIGHT
+ Update contributors

### CODE REVIEW

**Comment by magicae** [comment]
Review ready

**Comment by alvin-777** [comment]
Awesome!

**Comment by magicae** [comment]
对了 需要更新zh-TW和ja-JP翻译

**Comment by KochiyaOcean** [comment]
image
资源系的图标细节少一点似乎更好呢……

**Pull request merged**
