### PR TITLE
feat: add option to use quest contents in main panel

### PR DESCRIPTION
**Pull request by Werseter**
Adds an option in display tab allowing for using quests' description instead of name in main task panel.

I've tried to provide i18n translations, but they might require _a third party confirmation_
image
image

### CODE REVIEW

**Comment by gnattu** [comment]
A couple of things to note:
----
- The translated quest detail is provided by plugin, therefore the users who did not install the quest-info plugin, will get a long description from original game text, like this:
screen shot 2018-09-16 at 13 26 49

- Another problem is that, some quests have a very complicated requirement, made the quests panel not intuitively readable, example:
screen shot 2018-09-16 at 13 32 33
 In such case, you still have to move your mouse to see the full text in the popup.

------
Could you briefly explain why we need the description instead of name to be displayed  before we can merge this?

**Comment by Werseter** [comment]
The usability of such a feature depends on the side given to the panel. In english, the quest names are not translated, and do not give even a vague idea of what they mean, unless you aim for the pop-up. I personally would welcome such an option, as I've previously hardcoded it in, and now made it a configurable option.

**Comment by gnattu** [comment]
We did merge a proposed PR enables translation of quest names: https://github.com/poooi/poi/pull/1913

It was not landed because the data contains English translation was rejected: https://github.com/poooi/plugin-quest/pull/55

We still need to find a way to maintain such data without modifying current data structure too much, so there is still some time before the translated quest titles can be published.

Which one do you prefer? A translated title or a translated description?

**Comment by Werseter** [comment]
Personally, I think that getting the actual contents of the description provide more valuable info than the title. And the original title can be used to locate the quest in the Quest List (though I am working on a plugin that provides a display resembling the same exact view as the game does, with translated data, for easier quest location)

**Comment by Werseter** [comment]
Any status update on this? I'd like to swap to prebuilds for automatic updates, and by now this is the only reason for me to use the GitHub clone. Thanks to the prepared configurable option, this should pose no problems, and is off by default.

**Comment by gakada** [comment]
Currently title translations/interpretations can be supplemented with [plugin-translator](https://github.com/poooi/plugin-translator) or another plugin, they should be reasonably short and differ from descriptions. Some candidates for sourcing data:
- KC3Kai short names, not for plugin-translator as those are not translations, should work with an extra plugin though
- Either of two English wikis, should be ok for plugin-translator.

Though I can see this feature being useful, that is tooltips can have both titles and descriptions (both translated/interpreted via plugins or not), while the list can have an option to choose between titles and descriptions.

**Pull request closed without merging**
