### PR TITLE
OS Locale is handled as default

### PR DESCRIPTION
**Pull request by igax**
I'm a Japanese commodore.
I'd like to cooperate in localization. 
poi.

### CODE REVIEW

**Comment by Chibaheit** [comment]
THX. And we use the os-locale in the branch 4.0.0. Because the i18n is the newly feature. 
And can you help us check to localization in the i18n/ja_JP.json from the branch 4.0.0?

**Comment by zyc434343** [comment]
........

**Comment by zyc434343** [comment]
パソコンが苦手ですけど、これくらいのことはできるに決まってるだろう

**Comment by igax** [comment]
Okey. I'd like to help to improve ja_JP.json.

The Japanese message now is wonderful work, but the part where an expression is a little redundant is here.

Please break this pull request. I readjust ja_JP.json a little and send a pull request.
I'll soon sleep today, so it'll be tomorrow.  _(:3 」∠)_

telegram account: @futabachannel

**Comment by Chibaheit** [comment]
OK, THX

**Pull request closed without merging**
